using System;
using System.Runtime.Serialization;

namespace NSeed.Contracts
{
    /// <summary>
    /// The exception that is thrown if the date generated by a seed does not
    /// conform to the seed contract.
    /// </summary>
    internal class SeedContractViolationException : Exception
    {
        public SeedContractViolationException() { }

        public SeedContractViolationException(string message) : base(message) { }

        protected SeedContractViolationException(string message, Exception innerException) : base(message, innerException) { }

        protected SeedContractViolationException(SerializationInfo serializationInfo, StreamingContext streamingContext) : base(serializationInfo, streamingContext) { }
    }
}
